CC=g++

CXXFLAGS += -O2 -Wall

#My CPU security frags
#CXXFLAGS += -march=core-avx-i -pipe

all:
	$(MAKE) -C Bolha
	$(MAKE) -C Dado
	$(MAKE) -C Exemplo_Matriz
	$(MAKE) -C Jogo_Senha
	$(MAKE) -C Mega_Sena
	$(MAKE) -C Quadrangular
	$(MAKE) -C Random

clean:
	$(MAKE) clean -C Bolha
	$(MAKE) clean -C Dado
	$(MAKE) clean -C Exemplo_Matriz
	$(MAKE) clean -C Jogo_Senha
	$(MAKE) clean -C Mega_Sena
	$(MAKE) clean -C Quadrangular
	$(MAKE) clean -C Random

