CC=g++

PROGRAM=Dado

CXXFLAGS += -O2 -Wall

#My CPU security frags
#CXXFLAGS += -march=core-avx-i -pipe

	

all: $(PROGRAM)
	@echo "This is for Widnwos only"

clean:
	rm -rf $(PROGRAM)

run: $(PROGRAM)
	./$(PROGRAM)

test: $(PROGRAM)
	@./$(PROGRAM)
	@rm -rf $(PROGRAM)
